
IRREG_PLURALS = {
    "calf": "calves",
    "child": "children",
    "clothes" "clothes"
    "data": "data",
    "deer": "deer",
    "die": "dice",
    "elf": "elves" ,
    "glasses": "glasses",
    "goods": "goods",
    "goose": "geese",
    "half": "halves" ,
    "knife": "knives",
    "leaf": "leaves",
    "life": "lives",
    "loaf": "loaves",
    "man": "men",
    "many": "many" ,
    "mouse": "mice",
    "oats": "oats",
    "ox": "oxen",
    "pants": "pants",
    "person": "people",
    "pliers": "pliers",
    "scissors": "scissors",
    "self": "selves",
    "sheaf": "sheaves",
    "sheep": "sheep",
    "some": "some",
    "thanks": "thanks",
    "that": "that",
    "them": "them",
    "there": "there",
    "these": "these",
    "they": "they",
    "thief": "thieves",
    "those": "those",
    "tongs": "tongs",
    "trousers": "trousers",
    "trout": "trout" ,
    "which": "which",
    "wife": "wives",
    "woman": "women"}

IRREG_VERBS = {
    # "root", "present third person singular", "past", "present-participle", "past-participle"
    'become': {'present-third-person-singlular' : "becomes",
               'past' : "became",
               'present-participle' : "becoming",
               'past-participle' : "become"},
    "buy" : {'present-third-person-singular' : "buys",
             'past': "bought",
             'present-participle' : "buying",
             'past-participle' : "bought"},

    "come" : {'present-third-person-singular' : "comes",
            'past' : "came",
            'present-participle' : "coming",
            'past-participle' : "come"},
    "do" : {'present-third-person-singular' : "does",
          'past' : "did",
          'present-participle' : "doing",
          'past-participle' : "done"},
    "eat" : {'present-third-person-singular' : "eats",
           'past' : "ate",
           'present-participle' : "eating",
           'past-participle' : "eaten"},
    "fall" : {'present-third-person-singular' : "falls",
            'past' : "fell",
            'present-participle' : "falling",
            'past-participle' : "fallen"},
    "get" : {'present-third-person-singular' : "gets",
           'past' : "got",
           'present-participle' : "getting",
           'past-participle' : "gotten"},
    "give" : {'present-third-person-singular' : "gives",
            'past' : "gave",
            'present-participle' : "giving",
            'past-participle' : "given"},
    "go" : {'present-third-person-singular' : "goes",
          'past' : "went",
          'present-participle' : "going",
          'past-participle' : "gone"},
    "grow" : {'present-third-person-singular' : "grows",
            'past' : "grew",
            'present-participle' : "growing",
            'past-participle' : "grown"},
    "harbor" : {'present-third-person-singular' : "harbors",
              'past' : "harbored",
              'present-participle' : "harboring",
              'past-participle' : "harbored"},
    "have" : {'present-third-person-singular' : "has",
            'past' : "had",
            'present-participle' : "having",
            'past-participle' : "had"},
    "know" : {'present-third-person-singular' : "knows",
            'past' : "knew",
            'present-participle' : "knowing",
            'past-participle' : "known"},
    "leave" : {'present-third-person-singular' : "leaves",
             'past' : "left",
             'present-participle' : "leaving",
             'past-participle' : "left"},
    "make" : {'present-third-person-singular' : "makes",
            'past' : "made",
            'present-participle' : "making",
            'past-participle' : "made"},
    "see" : {'present-third-person-singular' : "sees",
           'past' : "saw",
           'present-participle' : "seeing",
           'past-participle' : "seen"},
    "take" : {'present-third-person-singular' : "takes",
            'past' : "took",
            'present-participle' : "taking",
            'past-participle' : "taken"},
    "throw" : {'present-third-person-singular' : "throws",
             'past' : "threw",
             'present-participle' : "throwing",
             'past-participle' : "thrown"},
    "undertake" : {'present-third-person-singular' : "undertakes",
                 'past' : "undertook",
                 'present-participle' : "undertaking",
                 'past-participle' : "undertaken"},
    "write" : {'present-third-person-singular' : "writes",
             'past' : "wrote",
             'present-participle' : "writing",
             'past-participle' : "written"}}


PRONOUNS_PERSON = {'third':'he', 
                   'first':"I", 
                   'second':'you'}

PRONOUNS_GENDER = {
    # key(masculine) feminine neuter
    'masculine':'he',
    'feminine':'she',
    'neuter':'it'}

PROUNOUNS_NUMBER = {
    "I": "we",
    'he': 'they',
    'she': 'they',
    'it': 'they'}

PRONOUNS_CASE = {
    #key(subjective) objective, possessive, reflexive
    "I": {'objective':"me", 
          'possessive': "mine", 
          'reflexive': "myself"},
    "you": {'objective':"you",
            'possessive': "yours",
            'reflexive': "yourself"},
    "he": {'objective':"him",
           'possessive': "his",
           'reflexive': "himself"},
    "she": {'objective':"her",
            'possessive': "hers"
            , 'reflexive': "herself"},
    "it": {'objective':"it", 
           'possessive': "its"
           , 'reflexive': "itself"},
    "we": {'objective':"us" , 
           'possessive': "ours", 
           'reflexive': "ourselves"},
    "they": {'objective':"them",
             'possessive': "theirs",
             'reflexive': "themselves" } } 

IRREG_SUPER_COMPARATIVES = {
    "good" : {'comparative': "better", 'seperlative':"best"},
    "bad" : {'comparative': "worse", 'seperlative':"worst"},
    "far" : {'comparative': "further", 'seperlative':"furthest"},
    "many" : {'comparative': "more", 'seperlative':"most"},
    "little" : {'comparative': "less", 'seperlative':"least"} }
