republican,n,y,n,y,y,y,n,n,n,y,?,y,y,y,n,y
republican,n,y,n,y,y,y,n,n,n,n,n,y,y,y,n,?
democrat,?,y,y,?,y,y,n,n,n,n,y,n,y,y,n,n
democrat,n,y,y,n,?,y,n,n,n,n,y,n,y,n,n,y
democrat,y,y,y,n,y,y,n,n,n,n,y,?,y,y,y,y
democrat,n,y,y,n,y,y,n,n,n,n,n,n,y,y,y,y
democrat,n,y,n,y,y,y,n,n,n,n,n,n,?,y,y,y
republican,n,y,n,y,y,y,n,n,n,n,n,n,y,y,?,y
republican,n,y,n,y,y,y,n,n,n,n,n,y,y,y,n,y
democrat,y,y,y,n,n,n,y,y,y,n,n,n,n,n,?,?
republican,n,y,n,y,y,n,n,n,n,n,?,?,y,y,n,n
republican,n,y,n,y,y,y,n,n,n,n,y,?,y,y,?,?
democrat,n,y,y,n,n,n,y,y,y,n,n,n,y,n,?,?
democrat,y,y,y,n,n,y,y,y,?,y,y,?,n,n,y,?
republican,n,y,n,y,y,y,n,n,n,n,n,y,?,?,n,?
republican,n,y,n,y,y,y,n,n,n,y,n,y,y,?,n,?
democrat,y,n,y,n,n,y,n,y,?,y,y,y,?,n,n,y
democrat,y,?,y,n,n,n,y,y,y,n,n,n,y,n,y,y
republican,n,y,n,y,y,y,n,n,n,n,n,?,y,y,n,n
democrat,y,y,y,n,n,n,y,y,y,n,y,n,n,n,y,y
democrat,y,y,y,n,n,?,y,y,n,n,y,n,n,n,y,y
democrat,y,y,y,n,n,n,y,y,y,n,n,n,?,?,y,y
democrat,y,?,y,n,n,n,y,y,y,n,n,?,n,n,y,y
democrat,y,y,y,n,n,n,y,y,y,n,n,n,n,n,y,y
democrat,y,n,y,n,n,n,y,y,y,n,n,n,n,n,y,?
democrat,y,n,y,n,n,n,y,y,y,y,n,n,n,n,y,y
democrat,y,n,y,n,n,n,y,y,y,n,y,n,n,n,y,y
democrat,y,y,y,n,n,n,y,y,y,n,y,n,n,n,y,y
republican,y,n,n,y,y,n,y,y,y,n,n,y,y,y,n,y
democrat,y,y,y,n,n,n,y,y,y,n,y,n,n,n,y,y
republican,n,y,n,y,y,y,n,n,n,n,n,y,y,y,n,n
democrat,y,y,y,n,n,n,y,y,y,n,y,n,n,n,y,?
democrat,y,y,y,n,n,n,y,y,y,y,n,n,y,n,y,y
republican,n,y,n,y,y,y,n,n,n,n,n,y,y,y,n,y
democrat,y,y,y,n,n,n,y,y,y,n,n,n,n,n,y,y
republican,n,y,n,y,y,y,n,n,n,n,n,y,y,y,n,n
republican,y,?,n,y,y,y,n,n,n,y,n,y,?,y,n,y
republican,y,y,n,y,y,y,n,n,n,n,n,n,y,y,n,y
republican,n,y,n,y,y,y,n,n,n,y,n,y,y,y,n,n
democrat,y,n,y,n,n,n,y,y,y,y,y,n,y,n,y,y
democrat,y,y,y,n,n,n,y,y,y,n,?,n,n,n,n,?
democrat,y,y,y,n,n,n,y,y,y,n,n,n,n,n,y,?
democrat,y,n,y,n,n,n,y,y,y,n,n,n,n,n,n,y
democrat,y,n,y,n,n,n,y,y,y,n,n,n,n,n,y,y
democrat,y,y,y,n,n,n,y,y,y,n,y,n,n,n,n,?
democrat,y,y,y,n,n,n,y,y,?,n,y,n,n,n,y,?
democrat,y,y,y,n,n,n,y,y,y,n,n,n,n,n,n,y
democrat,y,n,y,n,n,n,y,y,?,n,n,n,n,n,n,?
democrat,y,y,y,n,n,n,y,y,n,n,n,n,n,y,n,y
republican,n,?,n,y,y,y,n,n,n,n,n,y,y,y,n,n
democrat,y,y,y,n,n,n,y,y,y,n,y,n,n,n,y,y
republican,n,y,n,y,y,y,n,?,n,n,n,y,y,y,n,y
democrat,y,y,y,n,n,n,y,y,y,n,n,n,n,n,?,?
republican,y,y,n,y,y,y,n,n,n,y,n,y,y,y,n,n
democrat,y,y,y,n,n,y,?,y,n,n,y,y,n,y,n,?
republican,n,y,n,y,y,y,n,n,n,y,y,y,y,y,n,n
republican,n,y,n,y,y,y,n,n,n,y,y,y,y,y,n,y
republican,n,y,n,y,y,y,n,n,n,y,n,y,y,y,n,y
republican,n,y,n,y,y,y,n,n,n,y,n,y,y,y,n,y
republican,n,y,n,y,y,y,n,n,n,y,n,y,y,y,n,?
democrat,y,y,y,n,n,?,y,y,y,y,n,n,n,n,y,?
republican,n,y,n,y,y,y,n,n,n,n,n,y,y,y,n,n
democrat,y,y,y,n,n,n,y,y,y,n,n,n,n,n,n,?
democrat,y,y,y,n,n,n,y,y,y,n,y,n,n,n,n,y
democrat,y,y,y,n,n,n,y,y,y,n,y,?,n,n,n,y
republican,y,y,n,y,y,y,y,n,n,n,n,y,y,y,n,y
republican,n,y,n,y,y,y,y,n,n,n,y,y,y,y,n,y
republican,n,y,n,y,y,y,n,n,n,y,n,y,y,y,n,n
democrat,y,?,y,n,n,n,y,y,y,n,n,n,y,n,y,y
democrat,y,y,y,n,n,n,y,y,y,n,n,n,n,n,y,y
democrat,y,n,y,n,n,n,y,y,y,n,n,n,y,n,y,?
republican,y,y,y,y,n,n,y,y,y,y,y,n,n,y,n,y
democrat,y,y,y,n,n,n,y,y,y,n,y,n,n,n,y,?
republican,y,n,y,y,y,n,y,n,y,y,n,n,y,y,n,y
democrat,y,n,y,n,n,y,y,y,y,y,y,n,n,y,y,y
democrat,n,y,y,y,y,y,n,n,n,y,y,n,y,y,n,n
democrat,n,y,y,n,y,y,n,n,n,y,y,y,y,y,n,?
democrat,n,y,y,y,y,y,n,y,y,y,y,y,y,y,n,y
democrat,y,y,y,n,y,y,n,n,n,y,y,n,y,y,n,y
republican,n,n,n,y,y,n,n,n,n,y,n,y,y,y,n,n
democrat,y,n,y,n,n,y,y,y,y,y,n,y,n,y,n,?
democrat,y,n,y,n,n,n,y,y,?,y,y,y,n,y,n,y
republican,n,n,n,y,y,y,n,n,n,y,n,y,y,y,n,y
republican,n,n,n,y,y,y,n,n,n,n,n,y,y,y,n,n
republican,n,?,n,y,y,y,n,n,n,y,n,y,y,y,n,n
democrat,n,n,y,n,y,y,n,n,n,y,y,y,y,y,n,y
republican,n,n,n,y,y,y,n,n,n,y,n,y,y,y,n,n
republican,n,n,n,y,y,y,n,n,n,n,n,y,y,y,n,n
democrat,n,y,y,n,y,y,y,n,y,y,y,n,y,y,n,y
republican,n,n,n,y,y,y,n,n,n,y,n,?,y,y,n,?
democrat,y,n,y,n,n,n,y,y,y,y,n,n,n,n,y,y
democrat,y,n,y,n,n,n,y,y,y,y,y,n,n,n,y,y
democrat,y,y,y,n,n,n,y,y,n,y,y,n,n,?,y,y
democrat,y,n,y,n,n,n,y,n,y,y,y,n,n,n,y,y
democrat,y,n,y,n,y,y,n,n,n,n,n,n,n,n,n,y
democrat,y,n,y,n,y,y,n,?,?,n,y,?,?,?,y,y
democrat,n,n,?,n,y,y,n,n,n,n,y,y,y,y,n,y
democrat,y,n,n,n,y,y,y,n,n,y,y,n,n,y,n,y
democrat,y,y,y,n,n,y,y,y,y,y,n,n,n,n,n,y
republican,n,n,n,y,y,y,n,n,n,y,?,y,y,y,n,n
democrat,y,n,n,n,y,y,n,n,n,n,y,y,n,y,n,y
democrat,y,n,y,n,y,y,y,n,n,n,y,n,n,y,n,y
democrat,y,n,y,n,y,y,y,n,?,n,y,n,y,y,y,?
democrat,y,n,n,n,y,y,?,n,?,n,n,n,n,y,?,n
democrat,?,?,?,?,n,y,y,y,y,y,?,n,y,y,n,?
democrat,y,y,y,n,n,n,n,y,y,n,y,n,n,n,y,y
republican,n,y,n,y,y,y,n,n,n,n,n,y,y,y,n,y
republican,n,?,?,?,?,?,?,?,?,?,?,?,?,y,?,?
democrat,y,?,y,n,n,n,y,y,y,n,n,n,n,n,y,?
democrat,y,?,y,n,n,n,y,y,y,n,n,n,n,n,y,?
democrat,n,n,y,n,n,n,y,y,y,y,n,n,n,n,y,y
republican,n,?,n,y,y,y,n,n,n,y,n,y,y,y,n,y
democrat,n,?,y,n,n,y,y,y,n,y,n,n,n,n,y,?
republican,n,?,n,y,y,y,n,n,n,y,n,y,y,y,n,n
democrat,y,?,y,n,n,n,y,y,y,n,n,n,n,n,y,?
democrat,n,?,y,n,?,?,y,y,y,y,?,?,n,n,y,y
democrat,y,n,y,n,n,n,y,y,y,n,y,n,n,n,y,y
republican,y,y,y,y,y,n,y,n,n,n,n,y,y,y,n,y
democrat,n,y,y,n,n,n,n,y,y,y,y,n,n,n,y,y
republican,n,n,n,y,y,y,n,n,n,n,n,y,y,y,n,n
republican,n,?,?,y,y,y,n,n,n,y,n,y,y,y,?,y
republican,n,?,n,y,y,y,n,n,n,y,n,y,y,y,n,y
republican,n,n,n,y,y,y,n,n,n,y,n,y,n,y,n,y
republican,y,?,n,y,y,y,n,y,n,n,n,y,y,y,n,y
democrat,n,?,y,n,n,n,y,y,y,n,n,n,n,n,y,y
republican,n,?,n,y,y,y,n,n,n,y,n,y,y,y,n,y
republican,n,?,n,y,y,y,n,n,n,n,n,y,y,y,n,n
democrat,n,?,y,n,n,n,y,y,y,y,y,n,n,y,y,y
democrat,n,?,y,n,n,y,n,y,n,y,y,n,n,n,y,y
democrat,?,?,y,n,n,n,y,y,?,n,?,?,?,?,?,?
democrat,y,?,y,n,?,?,y,y,y,n,n,n,n,n,y,?
democrat,n,n,y,n,n,y,n,y,y,y,n,n,n,y,n,y
republican,n,n,n,y,y,y,n,n,n,y,n,y,y,y,n,?
republican,n,n,n,y,y,y,n,n,n,y,n,y,y,y,n,y
republican,n,n,n,y,y,y,n,n,n,n,n,y,y,y,n,?
republican,n,n,n,y,y,y,n,n,n,y,n,y,y,y,n,n
republican,n,y,n,y,y,y,n,n,n,y,y,y,y,n,n,y
democrat,n,?,y,n,n,y,y,y,y,y,n,n,n,y,y,y
democrat,n,n,y,n,n,y,y,y,y,y,n,n,n,y,n,y
democrat,y,n,y,n,n,y,y,y,y,n,n,n,n,n,y,y
republican,n,n,n,y,n,n,y,y,y,y,n,n,y,y,n,y
republican,n,n,n,y,y,y,y,y,y,y,n,y,y,y,?,y
republican,n,n,n,y,y,y,y,y,y,y,n,y,y,y,n,y
democrat,?,y,n,n,n,n,y,y,y,y,y,n,n,y,y,y
democrat,n,?,n,n,n,y,y,y,y,y,n,n,n,y,n,?
democrat,n,n,y,n,n,y,y,y,y,y,n,n,n,y,?,y
republican,n,y,n,y,y,y,n,n,n,n,n,y,y,y,n,y
democrat,n,n,n,n,n,n,y,y,y,y,n,y,y,y,y,y
republican,n,y,n,y,y,y,n,n,n,y,y,y,y,y,n,y
democrat,n,n,y,n,n,n,y,y,y,y,n,n,y,n,y,y
republican,y,y,n,y,y,y,n,n,n,y,n,y,y,y,n,y
democrat,y,y,?,y,y,y,n,n,y,n,y,?,y,y,n,n
democrat,n,y,y,n,n,y,n,y,y,y,y,n,y,n,y,y
democrat,n,n,y,n,n,y,y,y,y,y,y,n,y,y,n,y
republican,n,y,n,y,y,y,n,n,n,n,n,y,y,y,n,n
republican,y,y,n,y,y,y,n,?,n,n,y,y,y,y,n,n
republican,y,y,n,y,y,y,y,n,n,n,n,y,y,y,n,n
democrat,n,y,y,n,n,y,n,y,y,n,y,n,?,?,?,?
republican,n,y,n,y,y,y,n,n,n,y,n,y,y,y,n,n
democrat,n,y,y,n,?,y,y,y,y,y,y,n,n,?,n,?
democrat,n,y,n,n,y,y,n,n,n,n,n,y,y,y,y,y
democrat,n,n,n,n,y,y,y,n,n,n,n,y,y,y,n,y
democrat,n,y,y,n,y,y,y,n,n,n,y,y,y,y,n,y
republican,n,y,n,y,y,y,y,n,n,n,n,y,y,y,n,y
democrat,y,y,n,n,y,y,n,n,n,y,y,y,y,y,n,?
democrat,n,y,y,n,n,y,y,y,y,y,y,n,y,n,y,?
republican,y,n,y,y,y,y,y,y,n,y,n,y,n,y,y,y
republican,y,n,y,y,y,y,y,y,n,y,y,y,n,y,y,y
democrat,n,n,y,y,y,y,n,n,y,n,n,n,y,y,y,?
democrat,y,n,y,n,n,n,y,y,y,y,y,n,n,y,n,y
democrat,y,n,y,n,n,n,?,y,y,?,n,n,n,n,y,?
republican,n,?,n,y,y,y,n,n,n,y,n,y,y,y,n,y
democrat,n,y,y,n,n,n,y,y,y,y,n,n,?,n,y,y
democrat,n,n,n,n,y,y,n,n,n,y,y,y,y,y,n,y
democrat,y,?,y,n,n,n,y,y,y,n,n,n,n,n,y,?
democrat,n,y,y,n,n,n,y,y,y,y,n,n,n,n,y,y
republican,n,n,y,y,n,n,y,y,y,y,n,n,n,y,y,y
democrat,n,n,y,n,n,n,y,y,y,y,y,?,n,n,y,y
democrat,?,n,y,n,n,n,y,y,y,y,y,?,n,n,y,?
democrat,y,n,y,n,n,n,y,y,y,y,n,n,n,n,y,y
democrat,?,?,y,n,n,n,y,y,y,?,?,n,n,n,?,?
democrat,n,n,y,n,n,n,y,y,y,y,y,n,n,n,y,y
democrat,y,?,y,n,n,n,y,y,y,n,n,n,n,n,y,y
democrat,?,?,?,?,?,?,?,?,y,?,?,?,?,?,?,?
democrat,n,n,y,n,n,n,y,y,y,y,y,n,n,n,y,y
democrat,y,n,y,n,n,n,y,y,y,y,n,?,n,n,y,y
democrat,n,y,y,n,n,n,y,y,y,y,y,n,n,n,y,y
democrat,y,n,y,n,n,n,y,y,y,n,n,n,n,n,y,?
republican,y,?,n,y,y,y,y,y,n,n,n,y,?,y,?,?
democrat,y,n,y,n,n,n,y,y,y,n,n,n,n,n,y,y
republican,n,?,n,y,y,y,n,n,n,n,n,y,y,y,n,?
republican,n,y,n,y,y,y,n,?,n,y,n,y,y,y,n,?
democrat,n,n,n,n,n,y,y,y,y,n,y,n,n,y,y,y
democrat,n,n,y,n,n,n,y,y,y,n,n,n,n,n,y,y
democrat,n,n,y,n,n,y,y,?,y,y,y,n,n,n,y,y
republican,n,n,n,y,y,y,n,n,n,n,n,y,y,y,n,?
democrat,n,n,y,n,n,y,y,y,y,n,y,y,n,y,y,?
republican,n,?,y,y,y,y,n,n,n,y,n,n,n,y,n,y
democrat,n,n,y,n,n,n,y,y,y,y,y,n,?,n,y,?
democrat,y,y,n,n,n,n,y,y,?,n,y,n,n,n,y,?
democrat,n,n,y,n,n,n,y,y,y,n,n,n,n,y,y,y
democrat,y,y,y,n,n,n,y,y,y,n,n,n,n,n,y,y
democrat,y,n,y,n,n,y,y,y,y,y,y,n,n,n,y,y
democrat,y,n,y,n,n,n,y,y,y,y,n,n,n,n,y,y
republican,n,n,y,y,y,y,y,n,n,n,n,y,y,y,n,y
democrat,n,n,y,n,n,y,y,y,y,y,n,y,n,n,n,y
republican,n,n,n,y,y,y,n,n,n,y,n,y,n,y,n,y
republican,y,?,n,y,y,y,y,n,n,y,n,y,y,y,n,y
democrat,n,n,y,n,n,n,y,y,y,n,n,?,n,n,y,y
democrat,y,y,y,n,n,n,y,y,y,y,y,n,n,n,n,y
democrat,n,n,y,n,n,y,y,y,y,n,n,n,n,n,y,y
republican,n,y,n,y,y,y,n,n,n,y,n,y,y,y,n,y
democrat,n,n,y,n,n,n,y,y,y,n,y,n,n,n,y,y
democrat,n,y,y,n,n,y,n,y,y,n,y,n,y,n,y,y
republican,y,y,n,y,y,y,n,n,n,y,n,y,y,y,n,y
democrat,n,y,y,y,y,y,n,n,n,y,y,y,y,y,y,?
democrat,y,y,y,n,y,y,n,n,?,y,n,n,n,y,y,?
republican,n,y,n,y,y,y,n,n,n,y,n,y,y,y,n,n
democrat,y,?,y,n,n,n,y,y,y,n,?,n,n,n,y,?
democrat,n,y,y,n,n,n,n,y,y,n,y,n,n,y,y,y
democrat,n,n,y,n,n,n,y,y,y,n,n,n,n,n,y,?
democrat,n,y,y,n,y,y,n,n,n,n,y,n,n,n,y,?
democrat,y,n,y,n,n,n,y,y,y,n,y,n,n,n,y,?
republican,n,n,n,y,y,n,n,n,n,n,n,y,y,y,n,y
republican,n,y,n,y,y,y,n,n,n,y,n,?,y,y,n,n
republican,n,?,n,y,y,y,n,n,n,n,n,y,y,y,n,y
democrat,n,n,y,n,n,y,y,y,y,n,y,n,n,y,y,y
democrat,y,n,y,n,n,n,y,y,y,n,n,n,n,n,?,y
republican,n,y,n,y,y,y,n,n,n,n,n,y,y,?,n,y
republican,n,y,y,y,y,y,y,n,y,y,n,y,y,y,n,y
republican,n,y,n,y,y,y,n,n,n,n,n,y,y,y,n,y
republican,n,y,n,y,y,y,n,n,y,y,n,y,y,y,n,y
democrat,n,y,y,n,n,n,y,y,n,n,y,n,n,n,y,?
republican,n,y,n,y,y,y,n,n,n,y,n,y,y,y,n,y
democrat,n,n,y,n,n,y,y,y,y,y,n,y,n,y,y,?
republican,n,n,n,y,y,y,n,n,n,y,n,y,n,y,n,y
democrat,n,n,y,n,n,n,y,y,y,n,n,n,n,n,y,y
democrat,y,n,y,n,n,y,y,y,n,n,n,y,y,n,n,y
democrat,y,y,y,n,n,n,y,y,?,y,n,n,n,n,y,?
republican,n,n,n,y,y,y,y,n,n,y,n,n,n,y,y,y
republican,n,n,n,y,n,y,y,?,y,n,n,y,y,y,n,y
democrat,y,n,y,n,n,n,y,y,y,y,y,n,n,y,y,y
republican,n,n,n,n,y,y,y,n,n,n,n,?,n,y,y,y
democrat,n,y,y,n,n,n,y,y,?,y,n,n,y,n,y,y
democrat,y,n,y,n,n,n,n,y,y,y,n,n,n,n,y,y
democrat,y,n,y,n,n,n,y,y,y,y,y,n,n,n,y,y
democrat,n,n,y,n,y,n,y,y,y,n,n,n,n,y,?,y
republican,n,y,n,y,y,y,?,n,n,n,n,?,y,y,n,n
republican,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?
democrat,y,n,y,n,n,n,y,y,?,n,y,n,n,n,y,y
republican,n,y,n,y,y,y,n,n,n,n,n,y,y,y,n,n
republican,n,y,n,y,y,y,n,n,n,n,n,y,y,y,n,n
democrat,y,y,y,n,n,y,y,y,y,n,n,n,n,n,y,y
republican,n,y,n,y,y,y,n,n,n,n,n,y,y,y,n,y
democrat,y,n,y,n,n,n,y,y,y,y,n,n,n,n,n,y
democrat,y,n,y,n,n,n,y,y,y,y,n,n,n,y,y,y
republican,n,n,n,y,y,n,n,n,n,n,n,y,n,y,n,n
republican,n,n,n,y,y,n,n,n,n,n,n,y,n,y,?,y
democrat,n,n,y,n,n,n,y,y,y,n,y,n,n,n,y,y
democrat,y,n,y,n,n,n,y,y,y,n,n,n,n,n,n,y
democrat,y,n,y,n,n,n,y,y,y,y,n,n,n,n,n,y
democrat,y,n,y,n,n,?,y,y,y,n,?,?,n,?,?,?
democrat,y,n,y,n,n,n,y,y,y,y,n,n,?,n,y,y
democrat,y,n,y,n,n,n,y,y,y,n,n,n,n,n,y,?
democrat,y,n,y,n,n,n,y,y,y,n,n,n,n,n,y,?
democrat,y,n,y,n,n,n,y,y,y,y,n,n,n,n,n,y
republican,n,n,n,y,y,y,n,n,n,y,n,y,n,y,n,y
republican,y,n,n,n,n,n,y,y,y,y,n,n,n,y,n,y
democrat,y,n,y,n,n,n,y,y,y,n,n,n,n,n,y,?
democrat,y,n,y,n,n,n,y,y,y,n,n,n,n,n,n,y
democrat,y,y,y,n,n,n,y,y,y,n,n,n,n,n,y,y
democrat,n,y,y,n,n,y,y,y,y,n,?,n,n,n,n,y
democrat,y,n,y,n,n,n,y,y,y,y,n,n,n,n,y,?
republican,n,n,n,y,y,n,y,y,n,y,n,y,y,y,?,y
republican,y,n,n,y,y,n,y,n,n,y,n,n,n,y,y,y
democrat,n,n,y,n,y,y,n,n,n,n,?,n,y,y,n,n
republican,n,n,n,y,y,y,n,n,n,n,n,y,y,y,y,n
republican,n,n,y,y,y,y,y,y,n,y,n,n,n,y,n,y
republican,n,n,n,y,y,y,n,n,n,n,n,y,y,y,n,y
republican,n,n,n,y,y,y,n,n,n,y,n,y,y,y,n,n
democrat,n,n,y,n,n,n,y,y,y,y,n,n,n,y,n,y
republican,y,n,y,y,y,y,y,y,n,n,n,n,n,y,n,?
republican,y,n,n,y,y,y,n,n,n,y,n,?,y,y,n,n
republican,n,n,n,y,y,y,n,n,n,n,n,y,y,y,n,y
democrat,n,n,y,n,n,y,y,y,y,y,y,n,n,n,?,y
democrat,n,n,y,n,n,y,y,y,y,y,y,n,n,n,y,y
democrat,n,n,y,n,n,y,?,y,?,y,y,y,n,y,y,?
democrat,y,y,y,?,n,y,y,y,y,n,y,n,y,n,?,y
democrat,y,y,y,n,y,y,n,y,n,y,y,n,y,y,y,y
democrat,y,y,y,n,y,y,n,y,n,y,y,n,y,y,n,?
democrat,y,n,y,n,?,y,?,y,y,y,n,n,y,y,n,y
democrat,y,n,y,n,n,y,y,y,y,y,n,?,n,y,n,y
democrat,y,n,y,n,n,y,y,y,n,y,y,n,y,y,y,y
democrat,y,y,y,n,n,y,y,y,y,y,y,n,y,y,y,y
democrat,n,y,y,n,n,y,y,y,n,y,y,n,y,y,n,?
republican,n,y,n,y,y,y,?,?,n,y,n,y,?,?,?,?
republican,n,n,y,y,y,y,n,n,n,y,n,y,y,y,y,y
democrat,y,y,y,n,n,y,y,y,y,y,n,n,?,n,y,?
democrat,n,y,n,n,n,n,y,y,y,y,y,n,n,n,y,y
democrat,n,y,y,n,n,y,y,y,y,y,n,n,y,y,y,y
republican,n,n,n,y,y,n,y,y,y,y,n,y,y,y,n,y
democrat,n,n,?,n,n,y,y,y,y,n,n,n,n,n,y,y
republican,n,n,n,y,y,y,y,n,n,y,n,y,y,y,n,y
republican,n,n,n,y,y,y,n,n,n,n,n,y,y,y,n,n
republican,n,y,n,y,y,y,n,n,n,y,n,y,y,y,n,?
republican,n,n,n,y,y,y,n,n,n,y,n,y,y,y,n,n
republican,n,n,n,y,y,y,n,n,n,n,n,y,y,y,n,n
democrat,y,n,y,n,n,y,y,y,y,n,n,n,n,y,n,?
republican,n,n,n,y,y,y,n,n,n,y,n,y,y,y,n,n
democrat,y,n,n,n,n,y,y,y,y,y,n,n,n,y,y,y
republican,n,n,n,y,y,y,n,n,n,y,n,y,y,y,y,n
democrat,n,n,y,n,n,y,y,y,y,y,n,n,y,n,n,y
democrat,y,y,y,n,n,n,y,y,y,y,n,n,n,n,y,y
republican,n,y,y,y,y,y,n,n,n,y,n,y,y,y,n,y
republican,n,y,n,y,y,y,y,y,n,n,y,y,y,y,y,y
republican,n,y,y,y,y,y,y,?,n,n,n,n,?,?,y,?
democrat,n,n,n,n,n,y,n,y,y,n,y,y,y,y,y,n
democrat,y,n,n,n,n,n,y,y,y,y,n,n,n,n,y,y
democrat,n,n,y,n,n,n,y,y,y,n,n,n,n,n,y,?
democrat,y,n,y,n,n,n,y,y,y,n,n,n,n,n,y,?
democrat,n,y,y,n,n,y,n,y,y,y,n,n,y,y,n,y
democrat,y,y,y,n,n,n,y,y,y,y,n,n,y,n,n,y
democrat,y,y,y,n,?,y,n,?,n,n,y,n,y,y,n,?
democrat,y,y,y,n,y,y,n,y,?,y,n,n,y,y,n,?
republican,n,y,n,y,y,y,n,n,n,n,y,y,y,y,n,n
democrat,n,y,n,n,y,y,n,n,?,n,n,y,y,y,n,y
democrat,y,y,n,y,n,n,y,y,y,n,y,n,n,y,n,y
republican,n,y,n,y,y,y,n,n,n,n,n,y,y,y,n,y
democrat,y,y,y,n,n,n,y,y,y,n,y,n,n,n,n,y
democrat,y,?,y,n,n,y,y,y,y,y,n,n,n,n,y,?
republican,n,y,n,y,y,y,n,n,n,y,n,y,y,y,n,n
democrat,y,?,y,n,n,n,y,y,y,n,n,n,n,n,y,?
democrat,y,n,y,n,n,n,y,y,y,n,y,n,n,n,y,?
democrat,n,n,y,n,n,n,y,y,y,n,n,n,n,n,y,y
democrat,n,y,y,n,n,y,y,y,?,n,y,y,n,n,y,y
republican,n,n,n,y,y,y,n,n,n,y,y,y,y,y,n,?
democrat,n,n,y,n,n,y,y,y,n,n,y,n,n,y,?,y
democrat,y,n,y,n,n,n,y,y,y,n,n,n,n,n,y,y
democrat,y,n,y,n,n,n,y,y,y,y,n,n,n,y,y,y
republican,y,n,n,y,y,y,n,n,n,n,y,y,y,y,n,n
republican,n,n,n,y,y,y,n,n,n,y,y,y,n,y,n,y
democrat,n,?,y,?,n,y,y,y,y,y,y,n,?,?,y,y
democrat,n,y,y,n,y,?,y,n,n,y,y,n,y,n,y,y
republican,n,n,n,y,y,n,y,n,y,y,n,n,n,y,n,y
democrat,n,n,y,n,n,n,y,y,y,y,y,n,n,n,y,y
republican,n,n,n,y,y,y,y,n,n,y,n,y,n,y,y,y
republican,n,n,n,y,y,y,n,n,n,y,n,y,y,y,n,y
republican,y,n,n,y,y,y,n,n,n,y,n,y,y,y,n,n
democrat,y,n,y,n,n,n,y,y,y,y,n,y,n,n,y,?
republican,n,y,y,y,y,y,y,y,y,n,n,y,y,y,n,y
democrat,n,y,n,n,n,y,y,n,y,n,y,n,n,n,y,y
republican,n,n,y,y,y,y,y,y,y,y,n,y,y,y,y,y
democrat,n,y,n,y,n,y,y,y,y,n,y,n,y,n,y,?
republican,n,n,y,y,y,y,y,n,n,y,y,y,y,y,n,y
democrat,n,y,y,n,n,y,y,y,y,y,n,?,n,n,y,y
republican,y,n,y,y,n,n,n,y,y,y,n,n,n,y,y,y
republican,n,n,n,y,y,y,n,n,n,n,n,y,y,y,n,n
republican,n,n,n,y,y,y,n,n,n,n,n,y,y,y,n,n
democrat,y,y,y,n,n,y,y,y,y,y,y,y,y,y,n,?
republican,n,n,n,y,y,y,n,n,n,y,?,y,y,y,n,y
democrat,y,n,y,n,n,y,y,y,y,y,n,n,y,n,n,y
democrat,y,n,y,n,y,y,y,n,y,y,n,n,y,y,n,?
democrat,y,y,y,n,n,y,y,y,y,y,y,y,y,n,n,y
republican,y,y,n,y,y,y,n,n,n,y,y,n,y,n,n,n
republican,y,y,n,y,y,y,n,n,n,n,y,n,y,y,n,y
democrat,n,y,n,n,y,y,n,n,n,y,y,n,y,y,n,n
democrat,y,n,y,n,n,n,y,y,n,y,y,n,n,n,n,?
democrat,y,y,y,n,y,y,y,y,n,y,y,n,n,n,y,?
democrat,n,y,y,n,n,y,y,y,n,y,n,n,n,n,y,y
republican,n,y,n,y,y,y,n,n,n,n,n,n,y,y,n,y
democrat,y,y,y,n,?,y,y,y,n,y,?,?,n,n,y,y
democrat,y,y,y,n,?,n,y,y,y,y,n,n,n,n,y,?
democrat,n,y,y,y,y,y,n,n,n,n,y,y,?,y,n,n
democrat,n,y,y,?,y,y,n,y,n,y,?,n,y,y,?,y
republican,n,y,n,y,y,y,n,n,n,n,n,y,y,y,n,y
democrat,n,y,n,y,y,y,n,n,n,n,y,y,n,y,n,n
democrat,y,?,y,n,n,n,y,y,y,n,y,n,n,n,y,y
republican,n,y,n,y,y,y,?,?,n,n,?,?,y,?,?,?
republican,n,n,n,y,y,y,n,n,n,n,n,y,y,y,n,y
republican,n,n,n,y,y,y,n,n,n,n,n,y,y,y,n,y
democrat,y,y,y,n,n,y,?,y,y,n,y,n,y,n,y,y
democrat,y,y,y,n,y,y,y,y,y,y,y,n,y,y,n,?
democrat,y,y,n,y,y,y,n,n,n,n,y,n,y,y,n,?
democrat,y,y,y,n,y,y,n,y,y,y,y,n,n,n,n,y
democrat,y,y,y,y,y,y,n,n,n,n,y,y,y,y,n,y
democrat,y,y,n,n,y,y,n,n,n,n,y,y,y,y,y,n
democrat,n,?,y,n,y,y,n,y,n,n,y,n,n,n,n,?
democrat,y,y,y,n,y,y,n,y,y,n,y,n,n,y,n,?
democrat,n,y,y,y,y,y,n,n,n,n,n,y,y,y,n,?
democrat,y,n,y,n,n,n,y,y,y,?,y,n,n,n,y,?
democrat,?,?,n,n,?,y,?,n,n,n,y,y,n,y,n,?
democrat,y,y,n,n,n,n,n,y,y,n,y,n,n,n,y,n
republican,y,y,n,y,y,y,n,n,n,n,y,y,y,y,n,y
republican,?,?,?,?,n,y,n,y,y,n,n,y,y,n,n,?
democrat,y,y,?,?,?,y,n,n,n,n,y,n,y,n,n,y
democrat,y,y,y,?,n,n,n,y,n,n,y,?,n,n,y,y
democrat,y,y,y,n,y,y,n,y,n,n,y,n,y,n,y,y
democrat,y,y,n,n,y,?,n,n,n,n,y,n,y,y,n,y
democrat,n,y,y,n,y,y,n,y,n,n,n,n,n,n,n,y
republican,n,y,n,y,?,y,n,n,n,y,n,y,y,y,n,n
republican,n,y,n,y,y,y,n,?,n,n,?,?,?,y,n,?
republican,n,y,n,y,y,y,n,n,n,y,y,y,y,y,n,n
republican,?,n,y,y,n,y,y,y,y,y,n,y,n,y,n,y
republican,n,y,n,y,y,y,n,n,n,y,n,y,?,y,n,n
republican,y,y,n,y,y,y,n,n,n,y,n,y,y,y,n,y
republican,n,n,n,y,y,y,n,n,n,n,n,y,y,y,n,y
democrat,y,n,y,n,y,y,n,n,y,y,n,n,y,y,n,y
democrat,n,n,n,y,y,y,n,n,n,n,y,y,y,y,n,n
democrat,y,n,y,n,n,y,y,y,y,n,n,y,?,y,y,y
republican,n,n,n,y,y,y,n,n,n,n,n,y,y,y,n,n
republican,n,n,n,y,y,y,n,n,n,n,y,y,y,y,n,y
democrat,y,n,y,n,n,y,y,y,y,y,y,n,n,n,n,y
republican,n,n,n,y,y,y,n,n,n,y,n,y,y,y,n,y
republican,y,y,y,y,y,y,y,y,n,y,?,?,?,y,n,y
democrat,y,y,y,n,n,n,y,y,y,n,n,n,n,n,n,y
democrat,n,y,y,n,n,y,y,y,?,y,n,n,n,n,n,y
republican,y,y,n,y,y,y,n,n,n,y,n,n,y,y,n,y
democrat,y,y,y,n,n,n,y,y,y,y,y,n,y,n,n,y
democrat,y,y,y,n,n,n,y,y,n,y,n,n,n,n,n,y
democrat,y,y,y,n,n,n,y,y,y,n,n,n,n,n,n,y
republican,y,y,y,y,y,y,y,y,n,y,n,n,y,y,n,y
democrat,n,y,y,n,y,y,y,y,n,n,y,n,y,n,y,y
democrat,n,n,y,n,n,y,y,y,y,n,y,n,n,n,y,y
democrat,n,y,y,n,n,y,y,y,y,n,y,n,n,y,y,y
democrat,n,y,y,n,n,?,y,y,y,y,y,n,?,y,y,y
democrat,n,n,y,n,n,n,y,y,n,y,y,n,n,n,y,?
democrat,y,n,y,n,n,n,y,y,y,y,n,n,n,n,y,y
republican,n,n,n,y,y,y,y,y,n,y,n,y,y,y,n,y
democrat,?,?,?,n,n,n,y,y,y,y,n,n,y,n,y,y
democrat,y,n,y,n,?,n,y,y,y,y,n,y,n,?,y,y
republican,n,n,y,y,y,y,n,n,y,y,n,y,y,y,n,y
democrat,n,n,y,n,n,n,y,y,y,y,n,n,n,n,n,y
republican,n,?,n,y,y,y,n,n,n,n,y,y,y,y,n,y
republican,n,n,n,y,y,y,?,?,?,?,n,y,y,y,n,y
republican,n,y,n,y,y,y,n,n,n,y,n,y,y,y,?,n
