#!/bin/bash

# $0 = script path
# $1 = package path
# $2 = default location
# $3 = target volume

TMP=/tmp/nltk-installer/
cd $TMP
/usr/bin/sudo /Library/Frameworks/Python.framework/Versions/Current/bin/python ./setup.py install

# Clean up after ourselves by deleting /tmp/nltk-installer?
# rm -rf $TMP

export NLTK_DATA=/usr/share/nltk
echo export NLTK_DATA=/usr/share/nltk >> /.bashrc
