all: QuantizedLearner.class ContinuousLearner.class

QuantizedLearner.class: QuantizedLearner.java
	javac -classpath jahmm-0.2.6.jar QuantizedLearner.java

ContinuousLearner.class: ContinuousLearner.java
	javac -classpath jahmm-0.2.6.jar ContinuousLearner.java
