\+DatabaseType Word List- Aramaic
\ver 5.0
\desc This database type was generated by Shoebox for wordlist databases using the Aramaic language.
\+mkrset 
\lngDefault Default
\mkrRecord w

\+mkr c
\nam Count
\lng Default
\mkrOverThis w
\-mkr

\+mkr cz
\nam Count Sort
\desc Count field with leading zeros, for sorting by count.
\lng Default
\mkrOverThis w
\-mkr

\+mkr r
\nam References
\lng Default
\mkrOverThis w
\-mkr

\+mkr w
\nam Word
\lng Aramaic
\-mkr

\-mkrset
\iInterlinCharWd 8
\+filset 

\-filset
\+drflst 
\-drflst
\+template 
\-template
\mkrRecord w
\+PrintProperties 
\header File: &f, Date: &d
\footer Page &p
\topmargin 1.00 in
\leftmargin 0.25 in
\bottommargin 1.00 in
\rightmargin 0.25 in
\recordsspace 10
\-PrintProperties
\+expset 

\+expRTF Rich Text Format
\+rtfPageSetup 
\paperSize letter
\topMargin 1
\bottomMargin 1
\leftMargin 1.25
\rightMargin 1.25
\gutter 0
\headerToEdge 0.5
\footerToEdge 0.5
\columns 1
\columnSpacing 0.5
\-rtfPageSetup
\-expRTF

\+expSF Standard Format
\-expSF

\-expset
\-DatabaseType
