\NeedsTeXFormat{LaTeX2e}[1994/06/01]
\ProvidesClass{460}[2003/08/04 v1.0 460 class (SGB)]

\ProcessOptions
\LoadClass{article}
\usepackage{a4wide}
\usepackage{url}

\addtolength{\textheight}{2cm}
\setlength{\voffset}{-1.5cm}
\addtolength{\textwidth}{1cm}
\setlength{\hoffset}{-0.5cm}
\setlength{\parskip}{1ex}
\setlength{\parindent}{0ex}

\def\verbatim@font{\normalfont\ttfamily\small}

\title{433-460 Human Language Technology}
\def\num#1{\author{Assignment #1}}
\def\other#1{\author{#1}}
\def\due#1{\date{Due #1}}

\endinput
