%% This is LaTeX class `cis530', for making CIS-530 assigments

\NeedsTeXFormat{LaTeX2e}[1994/06/01]
\ProvidesClass{cis530}[2001/09/05 v1.0 CIS-530 class (SGB)]

\ProcessOptions
\LoadClass{article}

\addtolength\textwidth{2in}
\addtolength\textheight{1.6in}
\setlength\hoffset{-1in}
\setlength\voffset{-1in}
\setlength\parskip{1ex}
\setlength\parindent{0ex}

\title{CIS-530 Computational Linguistics}
\def\num#1{\author{Assignment #1}}
\def\other#1{\author{#1}}
\def\due#1{\date{Due #1}}

\endinput
