# NLTK-LITE: Tutorial Makefile
#
# Copyright (C) 2001-2005 University of Pennsylvania
# Author: Steven Bird <sb@csse.unimelb.edu.au>
#         Edward Loper <edloper@gradient.cis.upenn.edu>
# URL: <http://nltk.sf.net>
# For license information, see LICENSE.TXT

TUTORIALS = simple.txt

PDF := $(TUTORIALS:.txt=.pdf)
HTML := $(TUTORIALS:.txt=.html)
ERRS := $(TUTORIALS:.txt=.errs)

PYTHON = python
PDFLATEX = pdflatex #-halt-on-error
RST2HTML = ../rst.py --html
RST2LATEX = ../rst.py --latex

WEB = stevenbird@shell.sourceforge.net:/home/groups/n/nl/nltk/htdocs/lite
RSYNC_OPTS = -arvz -e ssh --relative --cvs-exclude

CSS_STYLESHEET_PATH = ../default.css
LATEX_STYLESHEET_PATH = ../definitions.sty

.SUFFIXES: .txt .html .pdf .errs

help: usage
usage:
	@echo "Usage:"
	@echo "    make all         -- Build HTML & PDF output"
	@echo "    make html        -- Build HTML output"
	@echo "    make pdf         -- Build PDF output"
	@echo "    make errs        -- Run doctest to generate .errs files"
	@echo "    make clean       -- Remove all built files"

all: $(HTML) $(PDF) clean_up
html: $(HTML)
pdf: $(PDF)
errs: $(ERRS)
	ls -l $(ERRS)

clean:
	rm -f $(PDF) $(HTML) $(ERRS) *.tex *.log *.aux *.out *.errs

clean_up:
	rm -f *.log *.aux *.tex *.out *.errs

.txt.html:
	$(RST2HTML) $<

.txt.tex:
	$(RST2LATEX) $<

.tex.pdf:
	$(PDFLATEX) $<

.txt.errs:
	$(PYTHON) -c "import doctest; doctest.testfile('$<')" > $@

rsync-en:
	rsync $(RSYNC_OPTS) . $(WEB)/doc/en/
