[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "nltk-extratokenizers"
version = "0.1.2"
description = "Core NLTK model/data files (punkt, tagger, stopwords, wordnet, etc.) packaged for pip installation"
authors = [
]
readme = "README.md"
requires-python = ">=3.8"
license = "Apache-2.0"
keywords = ["nltk", "nlp", "tokenizer", "punkt", "natural-language-processing"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Education",
    "Intended Audience :: Science/Research",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Text Processing :: Linguistic",
]
[project.urls]
Homepage = "https://github.com/Julien-ser/nltk_Group1_ENGG4450"
Repository = "https://github.com/Julien-ser/nltk_Group1_ENGG4450"
Issues = "https://github.com/Julien-ser/nltk_Group1_ENGG4450/issues"

[tool.setuptools.package-data]
"nltk_punkt" = [
  "data/tokenizers/punkt/*",
  "data/taggers/averaged_perceptron_tagger/*",
  "data/corpora/stopwords/*",
  "data/corpora/wordnet/*",
  "data/corpora/omw-1.4/*",
  "data/snowball_data/*",
  "data/corpora/names/*",
  "data/corpora/brown/*",
  "data/corpora/movie_reviews/*"
]

[project.entry-points."nltk_data"]
# Tokenizers
punkt = "nltk_punkt.data"

# Taggers
averaged_perceptron_tagger = "nltk_punkt.data"

# Corpora / lexical resources
stopwords = "nltk_punkt.data"
wordnet = "nltk_punkt.data"
"omw-1.4" = "nltk_punkt.data"
snowball_data = "nltk_punkt.data"
names = "nltk_punkt.data"
brown = "nltk_punkt.data"
movie_reviews = "nltk_punkt.data"
