# Natural Language Toolkit: Interface to TADM Classifier
#
# Copyright (C) 2001-2026 NLTK Project
# Author: Joseph Frazee <jfrazee@mail.utexas.edu>
# URL: <https://www.nltk.org/>
# For license information, see LICENSE.TXT

import math
import numbers
import sys

from nltk.internals import find_binary
from nltk.pathsec import TrustError, spawn_trusted

try:
    import numpy
except ImportError:
    pass

_tadm_bin = None


def config_tadm(bin=None):
    global _tadm_bin
    _tadm_bin = find_binary(
        "tadm", bin, env_vars=["TADM"], binary_names=["tadm"], url="http://tadm.sf.net"
    )


def _tadm_int(value, kind):
    # tadm's stdin is space and newline delimited. The "%d" interpolation already
    # rejects a string feature id/value with a TypeError, but validate up front so
    # a hostile or buggy encoding cannot inject a field or line (CWE-93) and the
    # error is clear. Reals are truncated as "%d" would; non-finite is refused.
    if isinstance(value, bool) or not isinstance(value, numbers.Real):
        raise ValueError(f"TADM {kind} must be a number, got {value!r}")
    if not math.isfinite(value):
        raise ValueError(f"TADM {kind} must be finite, got {value!r}")
    return int(value)


def write_tadm_file(train_toks, encoding, stream):
    """
    Generate an input file for ``tadm`` based on the given corpus of
    classified tokens.

    :type train_toks: list(tuple(dict, str))
    :param train_toks: Training data, represented as a list of
        pairs, the first member of which is a feature dictionary,
        and the second of which is a classification label.
    :type encoding: TadmEventMaxentFeatureEncoding
    :param encoding: A feature encoding, used to convert featuresets
        into feature vectors.
    :type stream: stream
    :param stream: The stream to which the ``tadm`` input file should be
        written.
    """
    # See the following for a file format description:
    #
    # https://sf.net/forum/forum.php?thread_id=1391502&forum_id=473054
    # https://sf.net/forum/forum.php?thread_id=1675097&forum_id=473054
    labels = encoding.labels()
    for featureset, label in train_toks:
        length_line = "%d\n" % len(labels)
        stream.write(length_line)
        for known_label in labels:
            v = encoding.encode(featureset, known_label)
            pairs = " ".join(
                "%d %d"
                % (_tadm_int(fid, "feature id"), _tadm_int(fval, "feature value"))
                for (fid, fval) in v
            )
            line = "%d %d %s\n" % (int(label == known_label), len(v), pairs)
            stream.write(line)


def parse_tadm_weights(paramfile):
    """
    Given the stdout output generated by ``tadm`` when training a
    model, return a ``numpy`` array containing the corresponding weight
    vector.
    """
    weights = []
    for line in paramfile:
        weights.append(float(line.strip()))
    return numpy.array(weights, "d")


def call_tadm(args):
    """
    Call the ``tadm`` binary with the given arguments.
    """
    if isinstance(args, str):
        raise TypeError("args should be a list of strings")
    if _tadm_bin is None:
        config_tadm()

    # Route through the trusted-exec chokepoint: verify the tadm binary is on a
    # path no other local user can swap, refuse a shell, and scrub the loader
    # environment before exec (CWE-426/427/732).
    cmd = [_tadm_bin] + args
    try:
        p = spawn_trusted(cmd[0], cmd[1:], stdout=sys.stdout)
    except TrustError as e:
        raise OSError(
            f"Refusing to run tadm at {cmd[0]!r}: it is not on a trusted path. "
            f"Install tadm where only you (or root) can write ({e})."
        ) from e
    (stdout, stderr) = p.communicate()

    # Check the return code.
    if p.returncode != 0:
        print()
        print(stderr)
        raise OSError("tadm command failed!")


def names_demo():
    from nltk.classify.maxent import TadmMaxentClassifier
    from nltk.classify.util import names_demo

    classifier = names_demo(TadmMaxentClassifier.train)


def encoding_demo():
    import sys

    from nltk.classify.maxent import TadmEventMaxentFeatureEncoding

    tokens = [
        ({"f0": 1, "f1": 1, "f3": 1}, "A"),
        ({"f0": 1, "f2": 1, "f4": 1}, "B"),
        ({"f0": 2, "f2": 1, "f3": 1, "f4": 1}, "A"),
    ]
    encoding = TadmEventMaxentFeatureEncoding.train(tokens)
    write_tadm_file(tokens, encoding, sys.stdout)
    print()
    for i in range(encoding.length()):
        print("%s --> %d" % (encoding.describe(i), i))
    print()


if __name__ == "__main__":
    encoding_demo()
    names_demo()
